---
- name: Install Worker Node for CentOs 
  hosts: all
  become: true 

  tasks:
    - name: Update packages
      yum:
        name: '*'
        state: latest
    
    - name: Print Installing Docker
      debug:
        msg: Installing Docker....
        
    - name: Install Docker Dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
    
    - name: Add Docker Repository to CentOS
      yum_repository:
        name: docker
        description: Docker repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      
    - name: Install Docker
      yum:
        name: docker-ce
        state: latest
        
    - name: Update containerd config
      command: containerd config default > /etc/containerd/config.toml

    - name: Make sure the service reboots
      systemd:
        state: restarted
        name: containerd

    - name: Make sure the service is enabled
      systemd:
        state: started
        name: containerd
        enabled: yes

    - name: Print Message
      debug:
        msg: Check Docker Status
    
    - name: Check docker status
      command: systemctl status docker

    - name: Print Message
      debug:
        msg: Install kubelet kubeadm kubectl

    - name: Create kubernetes.repo file
      lineinfile:
        dest: /etc/yum.repos.d/kubernetes.repo
        line: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=0
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        state: present

    - name: Install kubelet kubeadm kubectl
      yum:
        name:
          - kubelet 
          - kubeadm 
          - kubectl
        state: latest
    
    - name: Install NFS Utilities Package 
      yum:
        name: nfs-utils
        state: latest

    - name: Make sure the service is enabled
      systemd:
        state: started
        name: kubelet
        enabled: yes

    - name: Check kubelet status
      command: systemctl status kubelet
      
    - name: Remove swap from fstab
      shell: sed -i '/swap/d' /etc/fstab

    - name: Turn off swap space
      command: swapoff -a
    
    - name: Configure ip table
      lineinfile:
        dest: /etc/sysctl.d/k8s.conf
        line: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 0
        state: present

    - name: Apply system-level sysctl settings
      command: sysctl --system
  
    - name: Disable SELinux enforcement
      lineinfile:
        dest: /etc/selinux/config
        line: SELINUX=permissive
        regexp: '^SELINUX=enforcing$'
        state: present
      command: setenforce 0

    - name: Disable and stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

